### PR TITLE
Support tag values beeing undefined

### PR DESCRIPTION
**Pull request by starstuck**

### CODE REVIEW

**Comment by Licenser** [comment]
What are the circumstances this can happen under? I think having a `dvar` enforces that tag to be present, so it should at least be `<<>>` but never undefined.

**Comment by starstuck** [comment]
I will need to refresh my memory and test it again. Maybe it was down to some issue elsewhere. I will come back to you once I can describe the case.

**Comment by starstuck** [comment]
So I just have ran some simple test wit a simple query

`SELECT avg('base'.'cpu' FROM 'xxx') AS $unknown_tag LAST 10m`

You were right that dqe make sure that  `Gs` contains queried tag, but because it couldn't have been fetched from db, its value is undefined:

```[{{<<>>,<<"unknown_tag">>},undefined}]```

As a results `lists:keyfind`, finds the key but its value is undefined. Otherwise it would have returned `false`.

**Comment by Licenser** [comment]
yea but `AS $unknown_tag` kind of implies that the metrics looked up do have those tag doesn't it? At least that is my thinking on the matter, no series should be included there which doesn't have it to start with?

I am not sure I manage to explain my thoughts so I'll try with code:

`... AS $unknown_tag ...` is (or should be) a short hand version for `... WHERE $unknown_tag AS $unknown_tag ...` in my miund

**Comment by starstuck** [comment]
That would have sever practical implications and would also harm writing and reading concerns separation. We use some meta data for user information, for example uom. In my mind it does not make sense to require all writing processes provide that extra information, but once they do it is nice to show it.

**Comment by starstuck** [comment]
Also it is useful when introducing new tags as well. We can just start showing it without having to wait until all processes start writing it.

**Comment by Licenser** [comment]
The QE supports metadata for a while that can be attached to a series where there could be (or is alread, going to check right now) a clear differentiation between not set (`null`) and empty `""`. That sounds a lot more reasonable then trying to force metadata into a naming schema.

**Comment by starstuck** [comment]
OK. We can switch to meta data for those labels.

**Comment by Licenser** [comment]
Here an example of a query using metadata:

dalmatinerdb query 2017-06-06 18-18-41

**Comment by Licenser** [comment]
should be a propper undefined IMHO to make sure it's sensible, will fix that :) also cool!

**Pull request closed without merging**
